**DEPRECATED** see https://github.com/idn-au/idn-supermodel

= Indigenous Data Network's Supermodel

WARNING: in early development, not officially released yet

This Model - the IDN Supermodel - is the Australian Indigenous Data Network's overarching data model that provides integration logic for all elements of the IDN's data holdings.

It is currently in early development within a project being conducted for the IDN by https://surroundaustralia.com[SURROUND Australia Pty Ltd].

This model's document is auto-built from source files within the IDN Supermodel repository. Both the document and source files are viewable online.

The Specification document:

* https://surroundaustralia.github.io/idn-supermodel/supermodel.html

The repository:

* https://github.com/surroundaustralia/idn-supermodel

The online and repostory location will certainly change once this model is taken over by the IDN itself for continued use.

== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details.

== Contacts

Initial development of this work is being undertaken by the following, for the Indigenous Data Network:

**Nicholas J. Car** +
*Data Systems Architect* +
SURROUND Australia Pty Ltd. +  
<nicholas.car@surroundaustralia.com>  

**Peter Philips** +
*Analyst Programmer* +
SURROUND Australia Pty Ltd. +  
<peter.philips@surroundaustralia.com>  

**Margie Smith** +
*Data Manager* +
SURROUND Australia Pty Ltd. +  
<margie.smith@surroundaustralia.com>  
